// <auto-generated />
using System;
using CaseVeiculo.Data.Data.db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaseVeiculo.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240315205025_first")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaseVeiculo.Domain.Model.entities.AuditoriaVeiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HistoricoDeEstados")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId")
                        .IsUnique();

                    b.ToTable("AuditoriaDoVeiculo");
                });

            modelBuilder.Entity("CaseVeiculo.Domain.Model.entities.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("MarcaDoVeiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("CaseVeiculo.Domain.Model.entities.AuditoriaVeiculo", b =>
                {
                    b.HasOne("CaseVeiculo.Domain.Model.entities.Veiculo", "Veiculo")
                        .WithOne("AuditoriaDoVeiculo")
                        .HasForeignKey("CaseVeiculo.Domain.Model.entities.AuditoriaVeiculo", "VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("CaseVeiculo.Domain.Model.entities.Veiculo", b =>
                {
                    b.Navigation("AuditoriaDoVeiculo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
